services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/usr/src/app/logs
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

